Cleanup Visual Studio packages
DataDog/datadog-agent-buildimages pull request #621
Opened 2024-07-03 12:33 UTC by julien-lebot

## PR description
This PR cleans up the Visual Studio packages after https://github.com/DataDog/datadog-agent-buildimages/pull/540 because a lot of the packages selected were there for Visual Studio 2019.

## How to test
I've pulled the image from this pipeline: https://gitlab.ddbuild.io/DataDog/datadog-agent-buildimages/-/jobs/559678798 (image `486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/datadog-agent-buildimages/windows_1809_x64_test_only:v38129945-0d092098`) and set the C++ entrypoint `Platform Toolset` to `v142` (which matched Visual Studio 2019) and verified that it built successfully.

The downstream Agent pipeline passes as well.

2024-07-04 16:01 UTC, derekwbrown requested changes
As reported in slack; container still fails to build driver repo.

2024-07-15 14:46 UTC, iglendd approved these changes
What a pain :(

2024-07-15 14:46 UTC, iglendd commented on windows/helpers/phase1/install_vstudio.ps1
> +    "Microsoft.NetCore.Component.SDK",
I wonder how one can find and name all these packages?

2024-07-15 19:19 UTC, derekwbrown approved these changes

2024-07-16 09:19 UTC, merged